### PR TITLE
Fix filter ta/ command bug

### LINKED ISSUE #112: Bug: filter ta/ not working

### PR DESCRIPTION
**Pull request by T-Fang**
Fix #112

### CODE REVIEW

File: src/main/java/seedu/address/model/project/Participation.java [hunk 1]
```diff
@@ -83,6 +83,9 @@ public boolean hasTask(Task task) {
     public Person getPerson() {
         return person;
     }
+    public String getAssigneeName() {
+        return person.getFullName();
+    }
```
Comment (GeNiaaz) [inline src/main/java/seedu/address/model/project/Participation.java]: Maybe return a PersonName here instead of a string?

File: src/main/java/seedu/address/model/task/Task.java [hunk 2]
```diff
@@ -78,7 +78,7 @@ public boolean hasAssignee(Participation assignee) {
      */
     public boolean hasAssigneeWhoseNameIs(String assigneeName) {
         return assignees.stream()
-            .anyMatch(assignee -> assignee.getPerson().getPersonName().equals(assigneeName));
+            .anyMatch(assignee -> assignee.getAssigneeName().equals(assigneeName));
```
Comment (GeNiaaz) [inline src/main/java/seedu/address/model/task/Task.java:82]: Might be better to compare PersonName objects instead of strings

**Review by GeNiaaz — CHANGES_REQUESTED** [review]

**Review by GeNiaaz — APPROVED** [review]
Thanks for the changes, approved! 💯
